version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  - location: scripts/beforecicd.sh
    timeout: 300
    runas: root
  - location: scripts/aftercicd.sh
    timeout: 300
    runas: root
